global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 5
  width: 30.0
  height: 30.0
  resolution: 0.10
  obstacle_range: 5.0
  raytrace_range: 6.0
  origin_x: -15.0
  origin_y: -15.0
  static_map: true
  rolling_window: false

  plugins:
  - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  inflation_layer:
    enabled: true
    cost_scaling_factor: 15.0
    inflation_radius: 0.31