local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 20.0
   publish_frequency: 10.0
   width: 15.0
   height: 15.0
   resolution: 0.1
   static_map: false
   rolling_window: true
   obstacle_range: 5.0
   raytrace_range: 4.0

   plugins:
   - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

   inflation_layer:
      enabled: true
      cost_scaling_factor: 5.0
      inflation_radius: 0.31